import { useEffect, useState } from "react";
import api from "../api";
import { useAuth } from "../context/AuthContext";
import StatCard from "../components/StatCard";
import StatusBadge from "../components/StatusBadge";

export default function Dashboard(){
 const {user}=useAuth(); const [stats,setStats]=useState({}),[items,setItems]=useState([]),[notes,setNotes]=useState([]),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [s,n,d]=await Promise.all([api.get("/donations/stats"),api.get("/notifications"),api.get(user.role==="donor"?"/donations/mine":"/donations/ngo")]);setStats(s.data);setNotes(n.data.notifications);setItems(d.data.donations)}finally{setLoading(false)}};
 useEffect(()=>{load()},[user.role]);
 const changeStatus=async(id,status)=>{await api.patch(`/donations/${id}/status`,{status});load()};
 return <main className="section"><div className="container"><div className="page-title"><div><div className="eyebrow">{user.role==="ngo"?"NGO DASHBOARD":"DONOR DASHBOARD"}</div><h1>Hello, {user.name.split(" ")[0]} 👋</h1><p>{user.role==="ngo"?"Manage incoming collection requests and keep donors updated.":"Track your donations, pickups and community impact."}</p></div></div>
 {user.role==="ngo"&&!user.verified&&<div className="alert warning">Your NGO profile is awaiting admin verification. You can review your profile but only verified NGOs receive new donation requests.</div>}
 <div className="stats"><StatCard icon="🎁" label="Total donations" value={stats.total||0}/><StatCard icon="✓" label="Completed" value={stats.completed||0}/><StatCard icon="⏱" label="Active requests" value={stats.pending||0}/><StatCard icon="♻" label="Items donated" value={stats.quantity||0}/></div>
 <div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>{user.role==="ngo"?"Collection requests":"Donation history"}</h2><button className="btn btn-ghost" onClick={load}>Refresh</button></div>{loading?<div className="loader">Loading…</div>:!items.length?<div className="empty">No donations yet.</div>:<div className="table-wrap"><table><thead><tr><th>Item</th><th>{user.role==="ngo"?"Donor":"NGO"}</th><th>Pickup</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(d=><tr key={d._id}><td><b>{d.itemName}</b><small>{d.itemType} · Qty {d.quantity}</small></td><td>{user.role==="ngo"?d.donor?.name:d.ngo?.organizationName||d.ngo?.name}</td><td>{new Date(d.scheduledAt).toLocaleString([], {dateStyle:"medium",timeStyle:"short"})}</td><td><StatusBadge status={d.status}/></td><td>{user.role==="ngo"&&d.status==="Pending"?<div className="inline-actions"><button className="btn btn-small btn-primary" onClick={()=>changeStatus(d._id,"Accepted")}>Accept</button><button className="btn btn-small btn-danger" onClick={()=>changeStatus(d._id,"Rejected")}>Reject</button></div>:user.role==="ngo"&&d.status==="Accepted"?<button className="btn btn-small btn-primary" onClick={()=>changeStatus(d._id,"Scheduled")}>Schedule</button>:user.role==="ngo"&&d.status==="Scheduled"?<button className="btn btn-small btn-primary" onClick={()=>changeStatus(d._id,"Picked Up")}>Mark picked up</button>:user.role==="ngo"&&d.status==="Picked Up"?<button className="btn btn-small btn-primary" onClick={()=>changeStatus(d._id,"Distributed")}>Mark distributed</button>:<span className="muted">—</span>}</td></tr>)}</tbody></table></div>}</section>
 <aside className="panel"><div className="panel-head"><h2>Recent updates</h2></div>{notes.length?notes.slice(0,8).map(n=><div className={`notification ${n.read?"":"unread"}`} key={n._id}><b>{n.title}</b><p>{n.message}</p><small>{new Date(n.createdAt).toLocaleDateString()}</small></div>):<div className="empty">No notifications yet.</div>}</aside></div>
 </div></main>
}
